# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

evaluate: True 
test_max_iter: -1 
test_patch_size: null 
assert_checkpoint: True