# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

defaults:
  # if _self_ is the first entry, compositions will overwrite this config
  # if _self_ is the last entry, this config will overwrite compositions (default)
  # https://hydra.cc/docs/1.3/upgrades/1.0_to_1.1/default_composition_order/
  - preset: mini # ChangeS mini
  # - data: 200k
  - ../../equiformer/config/trainer_base
  - _self_

# batch_size: ${optim.batch_size}
# eval_batch_size: ${optim.eval_batch_size}

unsqueeze_e_dim: True # if to reshape model output [B] (OC20) -> [B,1] (MD17)
# squeeze_e_dim: False # if to reshape data [B,1] (MD17) -> [B] (OC20)
force_weight: 80
energy_weight: 1

model:
  name: equiformer_v2_md17 # equiformer_v2_oc20
  use_pbc: False                  # True for OC20 # use periodic boundary conditions
  # otf_graph:                True
  # regress_forces:           True
  max_neighbors: 1000           # 20 for OC20
  max_radius: 5.0               # 12.0 for OC20
