wandb_version: 1

output_dir:
  desc: null
  value: models/md17/deq-equiformer/test1
model_name:
  desc: null
  value: deq_dot_product_attention_transformer_exp_l2_md17
input_irreps:
  desc: null
  value: null
radius:
  desc: null
  value: 5.0
num_basis:
  desc: null
  value: 128
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 8
eval_batch_size:
  desc: null
  value: 24
model_ema:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.9999
model_ema_force_cpu:
  desc: null
  value: false
drop_path:
  desc: null
  value: 0.0
opt:
  desc: null
  value: adamw
opt_eps:
  desc: null
  value: 1.0e-08
opt_betas:
  desc: null
  value: null
clip_grad:
  desc: null
  value: null
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.005
sched:
  desc: null
  value: cosine
lr:
  desc: null
  value: 0.0005
lr_noise:
  desc: null
  value: null
lr_noise_pct:
  desc: null
  value: 0.67
lr_noise_std:
  desc: null
  value: 1.0
warmup_lr:
  desc: null
  value: 1.0e-06
min_lr:
  desc: null
  value: 1.0e-06
decay_epochs:
  desc: null
  value: 30
warmup_epochs:
  desc: null
  value: 10
cooldown_epochs:
  desc: null
  value: 10
patience_epochs:
  desc: null
  value: 10
decay_rate:
  desc: null
  value: 0.1
print_freq:
  desc: null
  value: 100
target:
  desc: null
  value: aspirin
data_path:
  desc: null
  value: datasets/md17
train_size:
  desc: null
  value: 950
val_size:
  desc: null
  value: 50
compute_stats:
  desc: null
  value: false
test_interval:
  desc: null
  value: 10
test_max_iter:
  desc: null
  value: 1000
energy_weight:
  desc: null
  value: 0.2
force_weight:
  desc: null
  value: 0.8
seed:
  desc: null
  value: 1
num_layers:
  desc: null
  value: 2
workers:
  desc: null
  value: 4
pin_mem:
  desc: null
  value: false
no_pin_mem:
  desc: null
  value: false
checkpoint_path:
  desc: null
  value: null
evaluate:
  desc: null
  value: false
meas_force:
  desc: null
  value: true
wandb:
  desc: null
  value: true
wandb_run_name:
  desc: null
  value: deq_dot_product_attention_transformer_exp_l2_md17
slurm_job_id:
  desc: null
  value: null
job_name:
  desc: null
  value: results
config_name:
  desc: null
  value: deq
override_dirname:
  desc: null
  value: ''
deq_mode:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1711115642.98051
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      - 77
      - 105
      2:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      - 77
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.16.3
      8:
      - 2
      - 5
      13: linux-x86_64
