# @package _global_
# ^^^ this @package directive solves any nesting problem (if this file is included in another folder)

defaults:
  # if _self_ is the first entry, compositions will overwrite this config
  # if _self_ is the last entry, this config will overwrite compositions (default)
  # https://hydra.cc/docs/1.3/upgrades/1.0_to_1.1/default_composition_order/
  - _self_
  # disable the output_subdir and logging of hydra
  - override /hydra/hydra_logging@_group_: none
  - override /hydra/job_logging@_group_: none

# disable the output_subdir and logging of hydra
hydra:
  output_subdir: null
  run:
    dir: .



# add stuff here



# variables we can access in our code
job_name: 'results'
# job_name: ${hydra:job.name}
config_name: ${hydra:job.config_name}
# Stores the command line arguments overrides
override_dirname: ${hydra:job.override_dirname}
# Changes the current working directory to the output directory for each job
# hydra.job.chdir: False