# @package _global_
# ^^^ this @package directive solves any nesting problem (if this file is included in another folder)

defaults:
  # if _self_ is the first entry, compositions will overwrite this config
  # if _self_ is the last entry, this config will overwrite compositions (default)
  # https://hydra.cc/docs/1.3/upgrades/1.0_to_1.1/default_composition_order/
  - equiformer: md17
  - _self_

# overwrite basem config
model_is_deq: True
deq_mode: True
num_layers: 2
# batch_size: 16

# deq args
deq_kwargs:
  # https://torchdeq.readthedocs.io/en/latest/torchdeq/core.html#torchdeq.core.get_deq
  # 'broyden' anderson newton
  # (str, optional) – The forward solver function. Default 'fixed_point_iter'
  f_solver: 'fixed_point_iter'.
  # (str, optional) – The backward solver function. Default 'fixed_point_iter'.
  b_solver: 'fixed_point_iter'
  # f_tol (float, optional) – The forward pass solver stopping criterion. Default 1e-3.
  f_tol: 1e-3
  # b_tol (float, optional) – The backward pass solver stopping criterion. Default 1e-6.
  b_tol: 1e-6
  # f_max_iter (int, optional) – Maximum number of iterations (NFE) for the forward solver. Default 40.
  f_max_iter: 40
  # b_max_iter (int, optional) – Maximum number of iterations (NFE) for the backward solver. Default 40
  b_max_iter: 40