# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

# Fixed-Point correction settings from DEQ Optical Flow paper

deq_kwargs:
  # core: sliced
  f_solver: 'anderson'
  f_stop_mode: 'rel'
  
# fpc_freq: 2
# fpreuse_test: True