# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

# All the normalizations

deq_kwargs:
  # core: sliced
  f_solver: 'broyden'
  f_stop_mode: 'rel'
  f_tol: 1e-2
  
# fpc_freq: 2
# fpreuse_test: True

model:
  torchdeq_norm:
    norm_type: weight_norm # weight_norm, spectral_norm
  path_drop: 0.05
  use_variational_path_drop: True

  ln: both
  ln_type: rms_norm_sh
  enc_ln: True
  inj_norm: null