# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

# https://github.com/atomicarchitects/equiformer_v2/blob/main/oc20/configs/s2ef/2M/equiformer_v2/equiformer_v2_N%4012_L%406_M%402.yml

# as close as possible to the original EquiformerV2 config

deq_kwargs:
  # core: sliced
  f_solver: 'anderson'
  f_stop_mode: 'rel'
  # f_tol: 1e-2
  # grad: 1
  # ift: True
  
# fpc_freq: 2
# fpreuse_test: True

model:
  torchdeq_norm:
    norm_type: null
  path_drop: 0.05
  use_variational_path_drop: True