# @package _global_
# ^^^ this @package directive solves any nesting problem (if this file is included in another folder)

# Fixed-Point correction settings, reweighted
#  +use=deq +cfg=fpc_of deq_kwargs.core=indexing fpc_weight=1e4 fpc_freq=3 deq_kwargs.f_stop_mode=rel deq_kwargs.f_tol=1e-4

deq_kwargs:
  f_max_iter: 24
  core: indexing
  f_solver: 'broyden'
  fpc_weight: 1e4 
  f_stop_mode: rel 
  # f_tol: 1e-4

fpc_freq: 3 
fpreuse_test: True