# @package _global_
# ^^^ this @package directive solves any nesting problem (if this file is included in another folder)

# Fixed-Point correction settings, reweighted

deq_kwargs:
  f_max_iter: 24
  f_solver: 'broyden'
  fpc_weight: 1e4 
  f_stop_mode: rel 
  f_tol: 1e-4

fpc_freq: 3 
fpreuse_test: True