# @package _global_
# ^^^ this @package directive solves any nesting problem (if this file is included in another folder)

# Settings from DEQ Optical Flow paper

deq_kwargs:
  f_max_iter: 24
  f_solver: 'broyden'

fpc_freq: 2