# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

# SGDR - Stochastic Gradient Descent with Warm Restarts

sched: "cosine"
lr_cycle_epochs: 10 
lr_cycle_mul: 2 
lr_cycle_limit: 0
decay_rate: 1.0 
cooldown_epochs: 0 
patience_epochs: 0
warmup_lr: 0 
warmup_epochs: 0